### ISSUE TITLE
Add the possibility to add perturbation to the field (at least in Fortran)

### ISSUE THREAD

**Issue by clementval** [MeteoSwiss-APN/serialbox#48]
With the old dumper we had the possibility to perturb the field while reading them. 

there is a module `m_preturb` that we could add to the fortran lib. 

A `!$ser mode read-perturb` could generate the code that allow this perturbation

**Comment by clementval** [comment]
Two solutions are envisaged: 

1 Using the python interface and doing an offline perturbation
2 Modifying the C++ directly and adding a `read_perturb` mode callable from Fortran as well

Example of how if was done before can be found in https://github.com/MeteoSwiss-APN/cosmo-pompa/blob/master/cosmo/src/m_perturb.f90

**Comment by cosunae** [comment]
Concerning the C++, my feeling is that this is a functionality belongs to the layer that owns and manages the field (i.e. the stella or gridtools storage or cosmo fortran fields), while the serialbox does not even know how to interpret the field. In that case, why not keeping it in cosmo? 
On the other hand, in python as a tool that operates on serialized data seems perfectly fine

**Comment by pspoerri** [comment]
Xavier suggested the idea of providing it directly in C++ instead of Fortran as this would allow us to integrate the feature later into C++. It is also easier to integrate it into Serializer directly instead of Fortran/Python because the Serializer does know about the fields and their types. 
- In Python we might run into problems because Python natively only supports Double precision and Serialbox does a Bytewise copy.
- Fortran is Fortran and a problem itself.

**Comment by clementval** [comment]
@pspoerri So what do we do for this feature? We should take a decision and dispatch the tasks to be done on it.

**Comment by pspoerri** [comment]
We do the scrum planning tomorrow. Let's see then.
