### ISSUE TITLE
Add error in case .dat file is not present

### ISSUE THREAD

**Issue by clementval** [MeteoSwiss-APN/serialbox#59]
If the .dat file is not present, a segfault is thrown. A nice error message would be better. 

This behavior has been seen from Fortran. I don't know if it has the same behavior if we use the C++ library only.

**Comment by PallasKat** [comment]
I add that if the .json file is missing (or misspelled prefix) we get an exception stating that the savepoint is missing instead of stating that the file is missing:

terminate called after throwing an instance of 'ser::SerializationException'
  what():  Error: the requested savepoint verif-radiation.input[ iteration=0 ] does not exist in the serializer.

**Comment by havogt** [comment]
Seems to be fixed in Serialbox2
```
Serialbox: ERROR: cannot open file: './SerialboxTest_ser_a.dat'
```
and
```
Serialbox: ERROR: cannot create Serializer: MetaData-SerialboxTest.json not found in "."
```
